namespace Application.Core
{
    using System;
    using UnityEngine;

    /// <summary>
    /// Different types of collision that can be registered by a trigger.
    /// </summary>
    public enum CollisionType
    {
        /// <summary>
        /// A rigidbody.
        /// </summary>
        Rigidbody,

        /// <summary>
        /// A collider.
        /// </summary>
        Collider,
    }

    /// <summary>
    /// A trigger that hooks into the weird hierarchy structure generated by RealtimeCSG triggers.
    /// </summary>
    public class RealtimeCsgTrigger : Trigger
    {
        [SerializeField]
        private CollisionType collisionType = CollisionType.Collider;

        private TriggerEvents _triggerEvents;

        /// <inheritdoc/>
        public override event Action<GameObject> CollisionEnter;

        /// <inheritdoc/>
        public override event Action<GameObject> CollisionExit;

        private void Awake()
        {
            _triggerEvents = GetComponentInChildren<Collider>()
                .GetTriggerEvents();
        }

        private void OnEnable()
        {
            switch (collisionType)
            {
                case CollisionType.Rigidbody:
                    _triggerEvents.RigidbodyTriggerEnter += HandleRigidbodyEnter;
                    _triggerEvents.RigidbodyTriggerExit += HandleRigidbodyExit;
                    break;
                case CollisionType.Collider:
                    _triggerEvents.ColliderTriggerEnter += HandleColliderEnter;
                    _triggerEvents.ColliderTriggerExit += HandleColliderExit;
                    break;
                default: throw new ArgumentOutOfRangeException(string.Empty);
            }
        }

        private void OnDisable()
        {
            _triggerEvents.RigidbodyTriggerEnter -= HandleRigidbodyEnter;
            _triggerEvents.RigidbodyTriggerExit -= HandleRigidbodyExit;
            _triggerEvents.ColliderTriggerEnter -= HandleColliderEnter;
            _triggerEvents.ColliderTriggerExit -= HandleColliderExit;
        }

        private void HandleRigidbodyEnter(Rigidbody rb)
        {
            CollisionEnter?.Invoke(rb.gameObject);
        }

        private void HandleRigidbodyExit(Rigidbody rb)
        {
            CollisionExit?.Invoke(rb.gameObject);
        }

        private void HandleColliderEnter(Collider col)
        {
            CollisionEnter?.Invoke(col.gameObject);
        }

        private void HandleColliderExit(Collider col)
        {
            CollisionExit?.Invoke(col.gameObject);
        }
    }
}
